/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:8c164809-a9ec-4ad8-9e7f-f07048c9d2ba",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ewIawpZwb",
    "aws_user_pools_web_client_id": "5ej06rn14moe5oodmc1jvmnb0h",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4a3ahs62enczjkz5ik6fld4nxq.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "backgroundimages211140-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
